### ISSUE TITLE
Using ember-cli for new book instead of EAK?

### ISSUE THREAD

**Issue by mech** [emberjsbook/rocknrollcall-eak#1]

**Comment by jessecravens** [comment]
Always the challenge of writing technical books. In the latest version (not yet released), I discuss Ember CLI in Chapter 3 on Tooling and Workflow, but unfortunately a complete switch would not make sense yet. Perhaps, in a later version.  From the ember-cli github README: "Although potentially exciting, this is still a work in progress project, use at your own risk."

**Comment by mech** [comment]
True, started kit and others are just besides the point. Core is the workflow and architecture sense.
